apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      schedulerName: sysdigsched
      containers:
      - name: nginx
        image: nginx
        ports:
        - name: http
          containerPort: 80
